### ISSUE TITLE
Define static variables

### ISSUE THREAD

**Issue by oltronix** [georgeflug/insomnia-plugin-save-variables#27]
I was wondering if it would be possible to add support for setting a variable to a static value. 

So in my scenario I have a number of requests set up that authenticates as different customers, and your plugin captures the token which is great, but to make things really smooth I would also like to set some other variables that are relevant for the customer but are not included in the response.

**Comment by georgeflug** [comment]
I like that idea. Can you confirm if I understand it correctly?

An example flow:
If you make Request A, then you want my_var to be assigned the static value "valA".
If you make Request B, then you want my_var to be assigned the static value "valB".
It does not matter what the response is for Request A or Request B because the assigned value is static.

**Comment by oltronix** [comment]
Yes exactly, that would enable me to define a number of values that are used in other subsecuent api calls in one 'starting point'.

So I could have a 'Get a token as Danish customer and set customerId to 12345 and email to this...' 
or 'Get token as English customer and set customerId to 2345 and email to this...'
And that would enable me to use the same suite of api calls to test different scenarios without any manual setup when changing scenarios.

**Comment by georgeflug** [comment]
This has been added in the latest version, 3.3.0

**Comment by oltronix** [comment]
Amazing, thank you very much!
